##### Question 1:

In [1]:
# (3/9*9/14)/(5/14)=3/5
print("P(Yes|Sunny) = 3/5")

P(Yes|Sunny) = 3/5


##### Question 2:

In [2]:
# Importing the required libraries.
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
%matplotlib inline

##### (a) Load iris dataset

In [10]:
dt = datasets.load_iris()
X = dt.data
y = dt.target

##### (b) Split the dataset into training and testing sets using train_test_split()

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

##### (c) Use GaussianNB

In [12]:
model = GaussianNB()

In [13]:
model.fit(X_train,y_train)

GaussianNB(priors=None)

In [14]:
pred = model.predict(X_test)

In [15]:
metrics.accuracy_score(y_test,pred)*100

95.55555555555556

##### i) Confusion matrix

In [17]:
print(confusion_matrix(y_test, pred))

[[16  0  0]
 [ 0 14  0]
 [ 0  2 13]]


##### ii) Classification report

In [16]:
print(metrics.classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.88      1.00      0.93        14
          2       1.00      0.87      0.93        15

avg / total       0.96      0.96      0.96        45



In [26]:
# Import MultinomialNB 
from sklearn.naive_bayes import MultinomialNB

##### (d) Use MultinomialNB

In [19]:
clf = MultinomialNB()

In [20]:
clf.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
pred2 = clf.predict(X_test)

In [22]:
metrics.accuracy_score(y_test,pred2)*100

100.0

##### i) Confusion matrix

In [25]:
print(confusion_matrix(y_test, pred2))

[[16  0  0]
 [ 0 14  0]
 [ 0  0 15]]


##### ii) Classification report

In [24]:
print(metrics.classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      1.00      1.00        14
          2       1.00      1.00      1.00        15

avg / total       1.00      1.00      1.00        45

