In [593]:
# Importing the required libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *
%matplotlib inline

__Load DataSet from sklearn.__

In [574]:
digit = load_digits()

In [575]:
X = digit.data
y = digit.target

In [576]:
X = StandardScaler().fit_transform(X)

__Perform PCA__

In [577]:
pca = PCA(n_components = 15)

In [578]:
x_new = pca.fit_transform(X)

In [579]:
x_new

array([[ 1.91420286, -0.95448087, -3.94606038, ...,  0.22509365,
        -0.20478637,  0.83409137],
       [ 0.58897975,  0.92464763,  3.92485722, ..., -0.03025759,
        -0.4167897 , -0.76794239],
       [ 1.3020248 , -0.31718255,  3.02339786, ..., -0.57820185,
        -0.98809882, -1.18001684],
       ...,
       [ 1.02265434, -0.14797941,  2.46974297, ..., -0.41589135,
         0.28171094,  0.35716094],
       [ 1.07615076, -0.38097848, -2.45580327, ...,  0.15655094,
        -0.75940223,  0.04019707],
       [-1.25765012, -2.22763073,  0.28346167, ...,  0.08484189,
         0.76323937,  1.86768782]])

In [592]:
#shape
x_new.shape

(1797, 15)

__Split data into training and testing sets.__

In [580]:
X_train, X_test, y_train, y_test = train_test_split(x_new, y, test_size=0.2, random_state=20)

__Perform logistic regression__

In [581]:
reg = LogisticRegression()

In [582]:
reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [583]:
predict = reg.predict(X_test)

__Accuracy Score__

In [584]:
accuracy_score(predict, y_test)*100

94.44444444444444

__Confusion Matrix__

In [585]:
print(confusion_matrix(predict, y_test))

[[37  0  0  0  0  1  0  0  0  0]
 [ 0 31  0  0  0  0  3  0  2  1]
 [ 0  0 27  1  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  1  0]
 [ 0  0  1  0 39  0  0  0  0  0]
 [ 0  0  0  0  0 32  0  0  0  1]
 [ 0  0  0  0  0  0 42  0  2  0]
 [ 0  0  0  2  0  0  0 40  1  1]
 [ 0  0  0  0  0  0  0  0 29  1]
 [ 0  0  0  0  2  0  0  0  0 28]]


__Classification Report__

In [586]:
print(classification_report(predict, y_test))

             precision    recall  f1-score   support

          0       1.00      0.97      0.99        38
          1       1.00      0.84      0.91        37
          2       0.96      0.96      0.96        28
          3       0.92      0.97      0.95        36
          4       0.95      0.97      0.96        40
          5       0.97      0.97      0.97        33
          6       0.93      0.95      0.94        44
          7       1.00      0.91      0.95        44
          8       0.83      0.97      0.89        30
          9       0.88      0.93      0.90        30

avg / total       0.95      0.94      0.94       360

